name: upload_files

on:
  push:
    branches: [ main, dev ]
    paths: ['gitbook/renewal/ja/**']
  pull_request:
    branches: [ main, dev ]
    paths: ['gitbook/renewal/ja/**']
  workflow_dispatch:

jobs:
  upload_file_gcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup gcloud for main
        if: github.ref == 'refs/heads/main' || github.base_ref == 'main'
        uses: google-github-actions/setup-gcloud@v2.1.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID_MAIN }}
          service_account_key: ${{ secrets.GCP_SA_KEY_MAIN }}
          export_default_credentials: true
      - name: Setup gcloud for dev
        if: github.ref == 'refs/heads/dev' || github.base_ref == 'dev'
        uses: google-github-actions/setup-gcloud@v2.1.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID_DEV }}
          service_account_key: ${{ secrets.GCP_SA_KEY_DEV }}
          export_default_credentials: true

      - name: create zip
        working-directory: ./
        run: zip -r ./help_center.zip ./gitbook/renewal/ja/
      - name: upload to GCS main
        if: github.ref == 'refs/heads/main' || github.base_ref == 'main'
        uses: google-github-actions/upload-cloud-storage@v2.1.0
        with:
          path: ./help_center.zip
          destination: ${{ secrets.GCP_BUCKET_MAIN }}
      - name: upload to GCS dev
        if: github.ref == 'refs/heads/dev' || github.base_ref == 'dev'
        uses: google-github-actions/upload-cloud-storage@v2.1.0
        with:
          path: ./help_center.zip
          destination: ${{ secrets.GCP_BUCKET_DEV }}
