name: upload_files

on:
  pull_request:
    branches: [ main, dev ]
    paths: ['gitbook/renewal/ja/**']
  workflow_dispatch:

jobs:
  upload_file_gcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ github.ref == 'refs/heads/main' ? secrets.GCP_PROJECT_ID_MAIN : secrets.GCP_PROJECT_ID_DEV }}
          service_account_key: ${{ github.ref == 'refs/heads/main' ? secrets.GCP_SA_KEY_MAIN : secrets.GCP_SA_KEY_DEV }}
          export_default_credentials: true
      - name: create zip
        working-directory: ./
        run: zip -r ./help_center.zip ./gitbook/renewal/ja/
      - id: upload-file
        uses: google-github-actions/upload-cloud-storage@main
        with:
          path: ./help_center.zip
          destination: ${{ github.ref == 'refs/heads/main' ? secrets.GCP_BUCKET_MAIN : secrets.GCP_BUCKET_DEV }}
