name: upload_files

on:
  pull_request:
    branches: [ main, dev ]
    paths: ['gitbook/renewal/ja/**']
  workflow_dispatch:

jobs:
  upload_file_gcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@v2.1.0
        if: github.ref == 'refs/heads/main'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID_MAIN }}
          service_account_key: ${{ secrets.GCP_SA_KEY_MAIN }}
          export_default_credentials: true
      - uses: google-github-actions/setup-gcloud@v2.1.0
        if: github.ref == 'refs/heads/dev'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID_DEV }}
          service_account_key: ${{ secrets.GCP_SA_KEY_DEV }}
          export_default_credentials: true

      - name: create zip
        working-directory: ./
        run: zip -r ./help_center.zip ./gitbook/renewal/ja/
      - id: upload-file-main
        if: github.ref == 'refs/heads/main'
        uses: google-github-actions/upload-cloud-storage@v2.1.0
        with:
          path: ./help_center.zip
          destination: ${{ secrets.GCP_BUCKET_MAIN }}
      - id: upload-file-dev
        if: github.ref == 'refs/heads/dev'
        uses: google-github-actions/upload-cloud-storage@v2.1.0
        with:
          path: ./help_center.zip
          destination: ${{ secrets.GCP_BUCKET_DEV }}
